// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/Permissions/ViewPermission.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Sales/BrowseSales.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Sales/ViewSale.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/UserPermissions/ViewUserPermission.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Users/ViewUser.lsml.js\"></script>");
