//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.UserPermission> MyPermissions(string PermissionName)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.UserPermission> query;
            string currentUser1 = global::Microsoft.LightSwitch.WellKnownPeople.CurrentUser();
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.UserPermission>("UserPermissions"),
                (u) => ((u.User.SharePointUser.CompareTo(currentUser1) == 0) && ((PermissionName == null) || u.Permission.Name.Contains(PermissionName))));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Sale))
            {
                return new global::LightSwitchApplication.Implementation.Sale();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Permission))
            {
                return new global::LightSwitchApplication.Implementation.Permission();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.UserPermission))
            {
                return new global::LightSwitchApplication.Implementation.UserPermission();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            string localConnectionString = this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                false);
            if (!string.IsNullOrEmpty(localConnectionString))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(localConnectionString);
            }
            else
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(new global::System.Data.EntityClient.EntityConnection(global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation.__workspace, this.__SqlAzureConnection));
            }
        }
    
        private static global::System.Data.Metadata.Edm.MetadataWorkspace __workspace = new global::System.Data.Metadata.Edm.MetadataWorkspace(new string[] { "res://*/ApplicationData.csdl", "res://*/ApplicationData.ssdl", "res://*/ApplicationData.msl" }, new global::System.Reflection.Assembly[] { global::System.Reflection.Assembly.GetExecutingAssembly() });
    
        private global::System.Data.SqlClient.SqlConnection ___sqlAzureConnection;
        private global::System.Data.SqlClient.SqlConnection __SqlAzureConnection
        {
            get
            {
                if (this.___sqlAzureConnection == null)
                {
                    using (global::Microsoft.SharePoint.Client.ClientContext context = global::LightSwitchApplication.Application.Current.SharePoint.GetHostWebClientContext())
                    {
                        bool isReadOnly;
                        if (global::Microsoft.SharePoint.Client.AppInstance.TryGetAppDatabaseConnectionDirect(context, out this.___sqlAzureConnection, out isReadOnly))
                        {
                            if (this.___sqlAzureConnection.State != global::System.Data.ConnectionState.Closed)
                            {
                                this.___sqlAzureConnection.Close();
                            }
                        }
                        else
                        {
                            this.ThrowDatabaseConnectionNotAvailableException();
                        }
                    }
                }
    
                return this.___sqlAzureConnection;
            }
        }
    
        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    if (this.___sqlAzureConnection != null)
                    {
                        this.___sqlAzureConnection.Dispose();
                    }
                }
            }
            finally
            {
                base.Dispose(disposing);
            }
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Sale))
            {
                return new global::LightSwitchApplication.Implementation.Sale();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Permission))
            {
                return new global::LightSwitchApplication.Implementation.Permission();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.UserPermission))
            {
                return new global::LightSwitchApplication.Implementation.UserPermission();
            }
            return null;
        }
    
    #endregion
    
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SharePointDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.SharePointData>
    {
    
        public SharePointDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).SharePointData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SharePointDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.AstoriaDataServiceImplementation<global::LightSwitchApplication.Implementation.SharePointData, global::SharePointData.SharePointDataService.AppCatalogDataContext>
    {
        public SharePointDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.UserInformationList))
            {
                return new global::LightSwitchApplication.Implementation.UserInformationList();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.SharePointData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.SharePointData(this.GetEntityConnectionString(
                "SharePointData",
                "res://" + assemblyName + "/SharePointData.csdl|res://" + assemblyName + "/SharePointData.ssdl|res://" + assemblyName + "/SharePointData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.UserInformationList))
            {
                return new global::LightSwitchApplication.Implementation.UserInformationList();
            }
            return null;
        }
    
        protected override string WebConfigurationConnectionStringName
        {
            get
            {
                return "SharePointData";
            }
        }
    
        protected override global::System.Type ConvertType(global::System.Type outerType)
        {
            if (outerType == typeof(global::LightSwitchApplication.Implementation.UserInformationList))
            {
                return typeof(global::SharePointData.SharePointDataService.UserInformationListItem);
            }
            return base.ConvertType(outerType);
        }
    
        protected override object ConvertEntity(object outerEntity)
        {
            global::LightSwitchApplication.Implementation.UserInformationList userInformationList = outerEntity as global::LightSwitchApplication.Implementation.UserInformationList;
            if (userInformationList != null)
            {
                global::SharePointData.SharePointDataService.UserInformationListItem result = new global::SharePointData.SharePointDataService.UserInformationListItem();
                result.OtherMail = userInformationList.OtherMail;
                result.Id = userInformationList.Id;
                result.ContentType = userInformationList.ContentType;
                result.CreatedById = userInformationList.CreatedById;
                result.ModifiedById = userInformationList.ModifiedById;
                return result;
            }
            return null;
        }
    
        protected override void UpdateResult(object outerEntity, object innerResult)
        {
            global::LightSwitchApplication.Implementation.UserInformationList outerUserInformationList = outerEntity as global::LightSwitchApplication.Implementation.UserInformationList;
            global::SharePointData.SharePointDataService.UserInformationListItem innerUserInformationList = innerResult as global::SharePointData.SharePointDataService.UserInformationListItem;
            if ((outerUserInformationList != null) && (innerUserInformationList != null))
            {
                outerUserInformationList.OtherMail = innerUserInformationList.OtherMail;
                outerUserInformationList.Id = innerUserInformationList.Id;
                outerUserInformationList.ContentType = innerUserInformationList.ContentType;
                outerUserInformationList.ContentTypeID = innerUserInformationList.ContentTypeID;
                outerUserInformationList.Name = innerUserInformationList.Name;
                outerUserInformationList.Account = innerUserInformationList.Account;
                outerUserInformationList.WorkEmail = innerUserInformationList.WorkEmail;
                outerUserInformationList.MobilePhone = innerUserInformationList.MobilePhone;
                outerUserInformationList.AboutMe = innerUserInformationList.AboutMe;
                outerUserInformationList.SIPAddress = innerUserInformationList.SIPAddress;
                outerUserInformationList.IsSiteAdmin = innerUserInformationList.IsSiteAdmin;
                outerUserInformationList.Deleted = innerUserInformationList.Deleted;
                outerUserInformationList.Hidden = innerUserInformationList.Hidden;
                outerUserInformationList.Picture = innerUserInformationList.Picture;
                outerUserInformationList.Department = innerUserInformationList.Department;
                outerUserInformationList.Title = innerUserInformationList.Title;
                outerUserInformationList.FirstName = innerUserInformationList.FirstName;
                outerUserInformationList.LastName = innerUserInformationList.LastName;
                outerUserInformationList.WorkPhone = innerUserInformationList.WorkPhone;
                outerUserInformationList.UserName = innerUserInformationList.UserName;
                outerUserInformationList.WebSite = innerUserInformationList.WebSite;
                outerUserInformationList.AskMeAbout = innerUserInformationList.AskMeAbout;
                outerUserInformationList.Office = innerUserInformationList.Office;
                outerUserInformationList.PictureTimestamp = innerUserInformationList.PictureTimestamp;
                outerUserInformationList.PicturePlaceholderState = innerUserInformationList.PicturePlaceholderState;
                outerUserInformationList.PictureExchangeSyncState = innerUserInformationList.PictureExchangeSyncState;
                outerUserInformationList.Modified = innerUserInformationList.Modified;
                outerUserInformationList.Created = innerUserInformationList.Created;
                outerUserInformationList.Owshiddenversion = innerUserInformationList.Owshiddenversion;
                outerUserInformationList.Version = innerUserInformationList.Version;
                outerUserInformationList.Path = innerUserInformationList.Path;
                outerUserInformationList.CreatedById = innerUserInformationList.CreatedById;
                outerUserInformationList.ModifiedById = innerUserInformationList.ModifiedById;
                return;
            }
            base.UpdateResult(outerEntity, innerResult);
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            if (dataServiceType == typeof(global::LightSwitchApplication.SharePointDataService))
            {
                return new global::LightSwitchApplication.SharePointDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.SharePointDataService))
            {
                return new global::LightSwitchApplication.Implementation.SharePointDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Sale) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Sale);
            }
            if (typeof(global::LightSwitchApplication.User) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.User);
            }
            if (typeof(global::LightSwitchApplication.Permission) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Permission);
            }
            if (typeof(global::LightSwitchApplication.UserPermission) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.UserPermission);
            }
            if (typeof(global::LightSwitchApplication.UserInformationList) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.UserInformationList);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Sale :
        global::LightSwitchApplication.Sale.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class User :
        global::LightSwitchApplication.User.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.UserPermissions
        {
            get
            {
                return this.UserPermissions;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Permission :
        global::LightSwitchApplication.Permission.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Permission.DetailsClass.IImplementation.UserPermissions
        {
            get
            {
                return this.UserPermissions;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UserPermission :
        global::LightSwitchApplication.UserPermission.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserPermission.DetailsClass.IImplementation.Permission
        {
            get
            {
                return this.Permission;
            }
            set
            {
                this.Permission = (global::LightSwitchApplication.Implementation.Permission)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Permission");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserPermission.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("User");
                }
            }
        }
        
        partial void OnUserPermission_PermissionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Permission");
            }
        }
        
        partial void OnUserPermission_UserChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("User");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class UserInformationList :
        global::LightSwitchApplication.UserInformationList.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.IAstoriaEntityImplementation
    {
    
        [global::System.Runtime.Serialization.DataMember]
        public string Microsoft_LightSwitch_ETag
        {
            get;
            set;
        }
    
        string global::Microsoft.LightSwitch.Internal.IAstoriaEntityImplementation.ETag
        {
            get { return this.Microsoft_LightSwitch_ETag; }
            set { this.Microsoft_LightSwitch_ETag = value; }
        }
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserInformationList.DetailsClass.IImplementation.CreatedBy
        {
            get
            {
                return this.CreatedBy;
            }
            set
            {
                this.CreatedBy = (global::LightSwitchApplication.Implementation.UserInformationList)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.UserInformationList.DetailsClass.IImplementation.ModifiedBy
        {
            get
            {
                return this.ModifiedBy;
            }
            set
            {
                this.ModifiedBy = (global::LightSwitchApplication.Implementation.UserInformationList)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        partial void OnCreatedByIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("CreatedBy");
            }
        }
        
        partial void OnModifiedByIdChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

