//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "UserInformationListItem_CreatedBy", "CreatedBy", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LightSwitchApplication.Implementation.UserInformationList), "UserInformationListItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.UserInformationList), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "UserInformationListItem_ModifiedBy", "ModifiedBy", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LightSwitchApplication.Implementation.UserInformationList), "UserInformationListItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.UserInformationList), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SharePointData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SharePointData object using the connection string found in the 'SharePointData' section of the application configuration file.
        /// </summary>
        public SharePointData() : base("name=SharePointData", "SharePointData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SharePointData object.
        /// </summary>
        public SharePointData(string connectionString) : base(connectionString, "SharePointData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SharePointData object.
        /// </summary>
        public SharePointData(EntityConnection connection) : base(connection, "SharePointData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserInformationList> UserInformationLists
        {
            get
            {
                if ((_UserInformationLists == null))
                {
                    _UserInformationLists = base.CreateObjectSet<UserInformationList>("UserInformationLists");
                }
                return _UserInformationLists;
            }
        }
        private ObjectSet<UserInformationList> _UserInformationLists;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserInformationLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserInformationLists(UserInformationList userInformationList)
        {
            base.AddObject("UserInformationLists", userInformationList);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="UserInformationList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInformationList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserInformationList object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static UserInformationList CreateUserInformationList(global::System.Int32 id)
        {
            UserInformationList userInformationList = new UserInformationList();
            userInformationList.Id = id;
            return userInformationList;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OtherMail
        {
            get
            {
                return _OtherMail;
            }
            set
            {
                OnOtherMailChanging(value);
                ReportPropertyChanging("OtherMail");
                _OtherMail = value;
                ReportPropertyChanged("OtherMail");
                OnOtherMailChanged();
            }
        }
        private global::System.String _OtherMail;
        partial void OnOtherMailChanging(global::System.String value);
        partial void OnOtherMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                OnContentTypeChanging(value);
                ReportPropertyChanging("ContentType");
                _ContentType = value;
                ReportPropertyChanged("ContentType");
                OnContentTypeChanged();
            }
        }
        private global::System.String _ContentType;
        partial void OnContentTypeChanging(global::System.String value);
        partial void OnContentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentTypeID
        {
            get
            {
                return _ContentTypeID;
            }
            set
            {
                OnContentTypeIDChanging(value);
                ReportPropertyChanging("ContentTypeID");
                _ContentTypeID = value;
                ReportPropertyChanged("ContentTypeID");
                OnContentTypeIDChanged();
            }
        }
        private global::System.String _ContentTypeID;
        partial void OnContentTypeIDChanging(global::System.String value);
        partial void OnContentTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                OnAccountChanging(value);
                ReportPropertyChanging("Account");
                _Account = value;
                ReportPropertyChanged("Account");
                OnAccountChanged();
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkEmail
        {
            get
            {
                return _WorkEmail;
            }
            set
            {
                OnWorkEmailChanging(value);
                ReportPropertyChanging("WorkEmail");
                _WorkEmail = value;
                ReportPropertyChanged("WorkEmail");
                OnWorkEmailChanged();
            }
        }
        private global::System.String _WorkEmail;
        partial void OnWorkEmailChanging(global::System.String value);
        partial void OnWorkEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MobilePhone
        {
            get
            {
                return _MobilePhone;
            }
            set
            {
                OnMobilePhoneChanging(value);
                ReportPropertyChanging("MobilePhone");
                _MobilePhone = value;
                ReportPropertyChanged("MobilePhone");
                OnMobilePhoneChanged();
            }
        }
        private global::System.String _MobilePhone;
        partial void OnMobilePhoneChanging(global::System.String value);
        partial void OnMobilePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AboutMe
        {
            get
            {
                return _AboutMe;
            }
            set
            {
                OnAboutMeChanging(value);
                ReportPropertyChanging("AboutMe");
                _AboutMe = value;
                ReportPropertyChanged("AboutMe");
                OnAboutMeChanged();
            }
        }
        private global::System.String _AboutMe;
        partial void OnAboutMeChanging(global::System.String value);
        partial void OnAboutMeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SIPAddress
        {
            get
            {
                return _SIPAddress;
            }
            set
            {
                OnSIPAddressChanging(value);
                ReportPropertyChanging("SIPAddress");
                _SIPAddress = value;
                ReportPropertyChanged("SIPAddress");
                OnSIPAddressChanged();
            }
        }
        private global::System.String _SIPAddress;
        partial void OnSIPAddressChanging(global::System.String value);
        partial void OnSIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSiteAdmin
        {
            get
            {
                return _IsSiteAdmin;
            }
            set
            {
                OnIsSiteAdminChanging(value);
                ReportPropertyChanging("IsSiteAdmin");
                _IsSiteAdmin = value;
                ReportPropertyChanged("IsSiteAdmin");
                OnIsSiteAdminChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSiteAdmin;
        partial void OnIsSiteAdminChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSiteAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = value;
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Hidden
        {
            get
            {
                return _Hidden;
            }
            set
            {
                OnHiddenChanging(value);
                ReportPropertyChanging("Hidden");
                _Hidden = value;
                ReportPropertyChanged("Hidden");
                OnHiddenChanged();
            }
        }
        private Nullable<global::System.Boolean> _Hidden;
        partial void OnHiddenChanging(Nullable<global::System.Boolean> value);
        partial void OnHiddenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = value;
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = value;
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = value;
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = value;
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = value;
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkPhone
        {
            get
            {
                return _WorkPhone;
            }
            set
            {
                OnWorkPhoneChanging(value);
                ReportPropertyChanging("WorkPhone");
                _WorkPhone = value;
                ReportPropertyChanged("WorkPhone");
                OnWorkPhoneChanged();
            }
        }
        private global::System.String _WorkPhone;
        partial void OnWorkPhoneChanging(global::System.String value);
        partial void OnWorkPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = value;
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebSite
        {
            get
            {
                return _WebSite;
            }
            set
            {
                OnWebSiteChanging(value);
                ReportPropertyChanging("WebSite");
                _WebSite = value;
                ReportPropertyChanged("WebSite");
                OnWebSiteChanged();
            }
        }
        private global::System.String _WebSite;
        partial void OnWebSiteChanging(global::System.String value);
        partial void OnWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AskMeAbout
        {
            get
            {
                return _AskMeAbout;
            }
            set
            {
                OnAskMeAboutChanging(value);
                ReportPropertyChanging("AskMeAbout");
                _AskMeAbout = value;
                ReportPropertyChanged("AskMeAbout");
                OnAskMeAboutChanged();
            }
        }
        private global::System.String _AskMeAbout;
        partial void OnAskMeAboutChanging(global::System.String value);
        partial void OnAskMeAboutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Office
        {
            get
            {
                return _Office;
            }
            set
            {
                OnOfficeChanging(value);
                ReportPropertyChanging("Office");
                _Office = value;
                ReportPropertyChanged("Office");
                OnOfficeChanged();
            }
        }
        private global::System.String _Office;
        partial void OnOfficeChanging(global::System.String value);
        partial void OnOfficeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PictureTimestamp
        {
            get
            {
                return _PictureTimestamp;
            }
            set
            {
                OnPictureTimestampChanging(value);
                ReportPropertyChanging("PictureTimestamp");
                _PictureTimestamp = value;
                ReportPropertyChanged("PictureTimestamp");
                OnPictureTimestampChanged();
            }
        }
        private global::System.String _PictureTimestamp;
        partial void OnPictureTimestampChanging(global::System.String value);
        partial void OnPictureTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PicturePlaceholderState
        {
            get
            {
                return _PicturePlaceholderState;
            }
            set
            {
                OnPicturePlaceholderStateChanging(value);
                ReportPropertyChanging("PicturePlaceholderState");
                _PicturePlaceholderState = value;
                ReportPropertyChanged("PicturePlaceholderState");
                OnPicturePlaceholderStateChanged();
            }
        }
        private Nullable<global::System.Int32> _PicturePlaceholderState;
        partial void OnPicturePlaceholderStateChanging(Nullable<global::System.Int32> value);
        partial void OnPicturePlaceholderStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PictureExchangeSyncState
        {
            get
            {
                return _PictureExchangeSyncState;
            }
            set
            {
                OnPictureExchangeSyncStateChanging(value);
                ReportPropertyChanging("PictureExchangeSyncState");
                _PictureExchangeSyncState = value;
                ReportPropertyChanged("PictureExchangeSyncState");
                OnPictureExchangeSyncStateChanged();
            }
        }
        private Nullable<global::System.Int32> _PictureExchangeSyncState;
        partial void OnPictureExchangeSyncStateChanging(Nullable<global::System.Int32> value);
        partial void OnPictureExchangeSyncStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Owshiddenversion
        {
            get
            {
                return _Owshiddenversion;
            }
            set
            {
                OnOwshiddenversionChanging(value);
                ReportPropertyChanging("Owshiddenversion");
                _Owshiddenversion = value;
                ReportPropertyChanged("Owshiddenversion");
                OnOwshiddenversionChanged();
            }
        }
        private Nullable<global::System.Int32> _Owshiddenversion;
        partial void OnOwshiddenversionChanging(Nullable<global::System.Int32> value);
        partial void OnOwshiddenversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = value;
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = value;
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatedById
        {
            get
            {
                return _CreatedById;
            }
            set
            {
                OnCreatedByIdChanging(value);
                ReportPropertyChanging("CreatedById");
                _CreatedById = value;
                ReportPropertyChanged("CreatedById");
                OnCreatedByIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatedById;
        partial void OnCreatedByIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatedByIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedById
        {
            get
            {
                return _ModifiedById;
            }
            set
            {
                OnModifiedByIdChanging(value);
                ReportPropertyChanging("ModifiedById");
                _ModifiedById = value;
                ReportPropertyChanged("ModifiedById");
                OnModifiedByIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedById;
        partial void OnModifiedByIdChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "UserInformationListItem_CreatedBy", "CreatedBy")]
        public UserInformationList CreatedBy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_CreatedBy", "CreatedBy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_CreatedBy", "CreatedBy").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserInformationList> CreatedByReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_CreatedBy", "CreatedBy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_CreatedBy", "CreatedBy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "UserInformationListItem_ModifiedBy", "ModifiedBy")]
        public UserInformationList ModifiedBy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_ModifiedBy", "ModifiedBy").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_ModifiedBy", "ModifiedBy").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserInformationList> ModifiedByReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_ModifiedBy", "ModifiedBy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserInformationList>("LightSwitchApplication.UserInformationListItem_ModifiedBy", "ModifiedBy", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
